defaults:
  - experiment: base

missing_data_strategy:
  _target_: ml.strategies.missing_data_strategy.DropMissingDataStrategy

categorical_data_strategy:
    _target_: ml.strategies.categorical_data_strategy.DropCategoricalStrategy

wandb:
  project: car_price_prediction
  entity: bertan-ulusoy
  raw_data_path: data/data.csv
  dest_path: output
  iteration_count: 5

sweep_config:
  method: bayes
  metric:
    name: MSE
    goal: minimize
  parameters:
    max_depth:
      distribution: int_uniform
      min: 1
      max: 20
    n_estimators:
      distribution: int_uniform
      min: 10
      max: 50
    min_samples_split:
      distribution: int_uniform
      min: 2
      max: 10
    min_samples_leaf:
      distribution: int_uniform
      min: 1
      max: 4